config/routes.rb
DownloadManager::Application.routes.draw do
  resources :folders do
    resources :folders
  end

  match 'uploads/:guest_token' => 'uploads#edit', :as=>:guest_upload, :constraints => {:guest_token => /([a-z0-9]*-){4}[a-z0-9]*/}

  resources :uploads do
    member do 
      post 'lock' #uploads/:id/lock
      post 'unlock' #uploads/:id/unlock
      get 'file' #uploads/:id/file
    end

    collection do #uploads/guest_upload
      get 'guest_upload'
    end

  end

  match 'users/login'=>'users#login'
  match 'users/logout'=>'users#logout'

   root :to => "uploads#index"

end

app/models/folder.rb
class Folder < ActiveRecord::Base

  has_many :uploads
  belongs_to :user

  has_many :folders
  belongs_to :folder
  
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_filter :login_required, :except => [:index, :show]

  # GET /folders
  # GET /folders.xml
  def index
    @folders = Folder.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @folders }
      format.json  { render :json => @folders }
    end
  end

  # GET /folders/1
  # GET /folders/1.xml
  def show
    @folder = Folder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @folder }
      format.json  { render :json => @folder }
    end
  end

  # GET /folders/new
  # GET /folders/new.xml
  def new
    @folder = Folder.new
    @parent_id = params[:folder_id].to_i
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @folder }
      format.json  { render :json => @folder }
    end
  end

  # GET /folders/1/edit
  def edit
    @folder = Folder.find(params[:id])
  end

  # POST /folders
  # POST /folders.xml
  def create
    @folder = Folder.new(params[:folder])

    @folder.user = current_user

    if params[:folder][:folder_id] == "0"
      @folder.folder = nil
    end    

    respond_to do |format|
      if @folder.save
        format.html { redirect_to(@folder, :notice => 'Folder was successfully created.') }
        format.xml  { render :xml => @folder, :status => :created, :location => @folder }
        format.json  { render :json => @folder, :status => :created, :location => @folder }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @folder.errors, :status => :unprocessable_entity }
        format.json  { render :json => @folder.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /folders/1
  # PUT /folders/1.xml
  def update
    @folder = Folder.find(params[:id])

    respond_to do |format|
      if @folder.update_attributes(params[:folder])
        format.html { redirect_to(@folder, :notice => 'Folder was successfully updated.') }
        format.xml  { head :ok }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @folder.errors, :status => :unprocessable_entity }
        format.json  { render :json => @folder.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.xml
  def destroy
    @folder = Folder.find(params[:id])
    @folder.destroy

    respond_to do |format|
      format.html { redirect_to(folders_url) }
      format.xml  { head :ok }
      format.json  { head :ok }
    end
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

<%= f.hidden_field :folder_id, :value => @parent_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<h1>Listing folders</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @folders.each do |folder| %>
  <tr>
    <td><%= folder.name %></td>
    <td><%= folder.user_id %></td>
    <td><%= link_to 'Show', folder %></td>
    <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
    <td><%= link_to 'Destroy', folder, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Folder', new_folder_path %>

app/views/folders/new.html.erb
<h1>New folder</h1>

<%= render 'form' %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= @folder.name %></b> owned by <%= @folder.user.login %>
</p>

<ul>
<% @folder.uploads.each do |upload| %>
  <li>
    <%= link_to upload.file_file_name, file_upload_path(upload) %>
    <%= render :partial => "layouts/move", :locals => {:upload => upload}%>
    <%= "(" + upload.user.login + ")" %>
  </li>
<% end %>
</ul>

<%= link_to 'Edit folder', edit_folder_path(@folder) %> |
<%= link_to 'Delete folder', @folder, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to "New subfolder", new_folder_folder_path(@folder) %>