config/routes.rb
DownloadManager::Application.routes.draw do
  resources :folders do
    resources :folders
  end

  match 'uploads/:guest_token' => 'uploads#edit', :as=>:guest_upload, :constraints => {:guest_token => /([a-z0-9]*-){4}[a-z0-9]*/}

  resources :uploads do
    member do 
      post 'lock' #uploads/:id/lock
      post 'unlock' #uploads/:id/unlock
      get 'file' #uploads/:id/file
    end

    collection do #uploads/guest_upload
      get 'guest_upload'
    end

  end

  match 'users/login'=>'users#login'
  match 'users/logout'=>'users#logout'

   root :to => "uploads#index"

end

app/models/upload.rb
require 'rubygems'
require 'uuid'

class Upload < ActiveRecord::Base
  attr_accessor :upload_type

  # Paperclip
  has_attached_file :file, :path => ":rails_root/uploads/:class/:id/:basename.:extension"
  #validates_attachment_presence :file

  validates :download_count, :presence=>true
  validates :user, :presence=>true
  
  belongs_to :folder
  belongs_to :user

  def self.unique_id
    UUID.new.generate
  end

  def guest_upload?
    !guest_token.nil?
  end

  def guest_link
    
  end
  
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_filter :login_required, :except => [:file, :index, :edit, :update]

  def file
    @upload = Upload.find(params[:id])

    unless @upload.locked?
      send_file @upload.file.path, :type => @upload.file_content_type, :disposition => 'inline'
      @upload.download_count+=1
      @upload.save!
    else
      flash[:error]="This file is locked."

      redirect_to(:controller=>"uploads")
    end
  end

  def lock
    set_locked(params[:id], true)

    redirect_to(:controller=>"uploads")
  end

  def unlock
    set_locked(params[:id], false)

    redirect_to(:controller=>"uploads")
  end

  def guest_upload
    @upload=Upload.new
    @upload.download_count=0
    
    @upload.user=current_user
    @upload.save!
  end

  # GET /uploads
  # GET /uploads.xml
  def index
    @uploads = Upload.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @uploads }
      format.json { render :json => @uploads }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.xml
  def new
    @upload = Upload.new
    @upload.upload_type= :normal
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @upload }
      format.json { render :json => @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    if params[:id]
      login_required
      @upload=Upload.find(params[:id])
    else
      @upload=Upload.find_by_guest_token(params[:guest_token])

      if @upload.file.exists?
        flash[:error]='File was already uploaded.'
        redirect_to :controller=>"uploads"
      end
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @upload }
      format.json { render :json => @upload }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.xml
  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @upload }
      format.json  { render :json => @upload }
    end
  end

  # POST /uploads
  # POST /uploads.xml
  def create
    @upload = Upload.new(params[:upload])
    @upload.download_count=0
    @upload.user=current_user

    if @upload.upload_type.eql? "guest"
      @upload.guest_token=Upload.unique_id

      description =params[:upload][:description]

      if description.empty?
        @upload.description="Guest upload opened by "+@upload.user.login
      else
        @upload.description=description
      end
    end

    respond_to do |format|
      if @upload.save
        flash[:notice]='Upload was successfully created.'

        if @upload.upload_type.eql? "guest"
          format.html { redirect_to(upload_path @upload) }
        else
          format.html { redirect_to(:controller=>"uploads") }
        end
        
        format.xml  { render :xml => @upload, :status => :created, :location => @upload }
        format.json  { render :json => @upload, :status => :created, :location => @upload }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @upload.errors, :status => :unprocessable_entity }
        format.json  { render :json => @upload.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.xml
  def update
    @upload = Upload.find(params[:id])

    flash[:notice]='Upload was successfully updated.'

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { 
          if @upload.folder
            redirect_to(@upload.folder)
          else
            redirect_to(:controller=>"uploads")
          end
        }
        format.xml  { head :ok }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @upload.errors, :status => :unprocessable_entity }
        format.json  { render :json => @upload.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.xml
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to(:controller=>"uploads") }
      format.xml  { head :ok }
      format.json  { head :ok }
    end
  end

  private

  def set_locked(upload_id, locked)
    @upload = Upload.find(upload_id)
    @upload.locked=locked
    @upload.save!
  end

end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= form_for(@upload,  :html => { :multipart => true }) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :file%>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 5 %>
  </div>

  <div class="field">
    <td><%= render :partial => "layouts/move", :locals => {:upload => @upload}%> </td>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/guest_upload.html.erb
<%= link_to "guest upload link", guest_upload_path(@upload.guest_token) %>

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<table>
  <thead>
    <th>file name</th>
    <th>file size</th>
    <th>owner</th>
    <th>download count</th>
    <th>description</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>

<% @uploads.each do |upload| %>
  <tr>

    <% if upload.file.exists? %>
      <td><%= link_to upload.file_file_name, file_upload_path(upload) %></td>
    <% else %>
      <td>
        <% if upload.guest_token %>
          <%= link_to "guest link", guest_upload_path(upload.guest_token) %>
        <% end %>
      </td>
    <% end %>

    <td><%= number_to_human_size(upload.file_file_size) %></td>
    <td><%= upload.user.login %></td>
    <td><%= upload.download_count %></td>
    <td><%= upload.description %></td>

    <% if upload.locked? %>
      <td><%= link_to 'Unlock', unlock_upload_path(upload), :method=>:post %></td>
    <% else %>
      <td><%= link_to 'Lock', lock_upload_path(upload), :method=>:post %></td>
    <% end %>

    <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
    <td><%= link_to 'Destroy', upload, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= form_for(@upload, :html => { :multipart => true }) do |f| %>
  
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>
      <%= f.radio_button(:upload_type, :normal) %> normal
      <%= f.radio_button(:upload_type, :guest) %> guest
    </p>
  </div>

  <div class="field">
    <%= f.file_field :file%>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/show.html.erb
<p>
  <%= link_to "guest upload link", guest_upload_path(@upload.guest_token) %>
</p>
<p>
  description:
  <br />
  <%= @upload.description %>
</p>