config/routes.rb
DownloadManager::Application.routes.draw do
  resources :folders do
    resources :folders
  end

  match 'uploads/:guest_token' => 'uploads#edit', :as=>:guest_upload, :constraints => {:guest_token => /([a-z0-9]*-){4}[a-z0-9]*/}

  resources :uploads do
    member do 
      post 'lock' #uploads/:id/lock
      post 'unlock' #uploads/:id/unlock
      get 'file' #uploads/:id/file
    end

    collection do #uploads/guest_upload
      get 'guest_upload'
    end

  end

  match 'users/login'=>'users#login'
  match 'users/logout'=>'users#logout'

   root :to => "uploads#index"

end

app/views/layouts/_folder_recursive.html.erb
<% current_folder_id = params[:id].to_i %>

<% folders.each do |folder| %>
    <li>
      <%= image_tag "dir.png" %>
      <% if folder.id == current_folder_id %>
        <%= link_to folder.name, folder, :class => "current_folder" %>
      <% else %>
        <%= link_to folder.name, folder %>
      <% end %>
      <% if folder.folders %>
      <ul>
        <%= render :partial => "layouts/folder_recursive", :locals => {:folders => folder.folders}  %>
      </ul>
      <% end %>
    </li>
    
<% end %>

app/views/layouts/_folders.html.erb
<% current_folder_id = params[:id].to_i %>

<ul class="folders">
  
  <%= render :partial => "layouts/folder_recursive",
    :locals => {:folders => folders}  %>

  <hr />

  <li>
    <%= image_tag "folder-new.png" %>
    <%= link_to "new folder", :controller => "folders", :action => "new" %>
  </li>

</ul>

app/views/layouts/_move.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= form_for upload do |f| %>

<%= f.select(:folder_id, all_folders_array) %>
<%= f.submit "move" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DownloadManager</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div class="header">

    Der neue schicke DownloadManager

  <ul class="navigation">
    <li><%= link_to "guest link", guest_upload_uploads_path %></li>
    <li><%= link_to "uploads", uploads_path %></li>
    <li><%= link_to "new upload", new_upload_path %> </li>
    <% if current_user %>
      <li><%= link_to "logout", users_logout_path %></li>
    <% else %>
      <li><%= link_to "login", users_login_path %></li>
    <% end %>
  </ul>

  </div>

  <% if flash[:error] %>
    <p id="alert"><%= flash[:error] %></p>
  <%  end %>

  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %> </p>
  <% end %>

  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <%  end %>

  <%= render :partial => "layouts/folders", :locals => {:folders => all_folders} %>


    <div class="content"><%= yield %></div>

</body>
</html>